# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: awscli

    env:
      AWS_CLI_AUTO_PROMPT=on-partial
    before:
     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
     unzip awscliv2.zip
     sudo ./aws/install
     cd $THEIA_WORKSPACE_ROOT
gp env AWS_ACCESS_KEY_ID=AKIAZQ3DU43SJTDADJ5G
gp env AWS_SECRET_ACCESS_KEY=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
gp env AWS_DEFAULT_REGION=ca-central-1