#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi
BUCKET_NAME=$1
aws s3api create-bucket --bucket mysuperduperbucket --region ca-central-1 --create-bucket-configuration LocationConstraint=ca-central-1