#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi
BUCKET_NAME=$1
# http://mysuperduperbucket-v2.s3.amazonaws.com/
aws s3api create-bucket \
--bucket "$BUCKET_NAME" \
--create-bucket-configuration LocationConstraint=ca-central-1 \
--query Location \
--output text

